## LDA Topic Modeling

In [54]:
import pandas as pd
data = pd.read_csv('data_cleaned_V4.csv',engine='python', dtype=str)
corpus=data['comment'].tolist()

In [55]:
import gensim
from gensim import corpora
from nltk.tokenize import word_tokenize

corpsplit=[word_tokenize(doc) for doc in data['comment']]
dictionary = corpora.Dictionary(corpsplit)
doc_term_matrix = [dictionary.doc2bow(doc) for doc in corpsplit]

In [31]:
Lda = gensim.models.ldamodel.LdaModel

#### num_topics=5

In [32]:
ldamodel = Lda(doc_term_matrix, num_topics=5, id2word = dictionary, passes=50)

In [33]:
print(ldamodel.print_topics(num_topics=5, num_words=5))

[(0, '0.007*"muslim" + 0.007*"culture" + 0.006*"refugee" + 0.006*"see" + 0.005*"would"'), (1, '0.015*"people" + 0.010*"car" + 0.007*"gay" + 0.007*"like" + 0.007*"love"'), (2, '0.019*"country" + 0.018*"people" + 0.010*"dont" + 0.009*"right" + 0.007*"want"'), (3, '0.010*"like" + 0.009*"good" + 0.008*"people" + 0.008*"dont" + 0.007*"illegal"'), (4, '0.014*"like" + 0.009*"heart" + 0.009*"get" + 0.008*"way" + 0.007*"refugee"')]


#### num_topics=10

In [34]:
ldamodel2 = Lda(doc_term_matrix, num_topics=10, id2word = dictionary, passes=50)

In [35]:
print(ldamodel2.print_topics(num_topics=10, num_words=10))

[(0, '0.020*"heart" + 0.012*"url" + 0.011*"lord" + 0.008*"even" + 0.007*"love" + 0.007*"fake" + 0.007*"donald" + 0.007*"doe" + 0.006*"way" + 0.006*"get"'), (1, '0.011*"like" + 0.007*"people" + 0.007*"want" + 0.006*"please" + 0.006*"military" + 0.006*"war" + 0.005*"life" + 0.005*"wont" + 0.005*"god" + 0.005*"government"'), (2, '0.016*"world" + 0.014*"people" + 0.009*"trump" + 0.008*"equal" + 0.007*"culture" + 0.007*"country" + 0.007*"need" + 0.007*"would" + 0.007*"dont" + 0.007*"refugee"'), (3, '0.024*"people" + 0.017*"country" + 0.014*"dont" + 0.014*"like" + 0.010*"gay" + 0.010*"right" + 0.009*"think" + 0.008*"get" + 0.007*"would" + 0.007*"wall"'), (4, '0.021*"gay" + 0.013*"dont" + 0.012*"like" + 0.011*"would" + 0.009*"word" + 0.009*"cake" + 0.006*"video" + 0.006*"islam" + 0.006*"know" + 0.006*"terrorist"'), (5, '0.011*"muslim" + 0.011*"islam" + 0.010*"country" + 0.008*"make" + 0.008*"fuck" + 0.007*"know" + 0.006*"refugee" + 0.005*"video" + 0.005*"anyone" + 0.005*"fat"'), (6, '0.028*"c

#### num_topics=20

In [36]:
ldamodel3 = Lda(doc_term_matrix, num_topics=20, id2word = dictionary, passes=50)

In [37]:
print(ldamodel3.print_topics(num_topics=20, num_words=10))

[(0, '0.019*"illegal" + 0.017*"let" + 0.010*"quran" + 0.010*"find" + 0.008*"immigrant" + 0.008*"going" + 0.008*"take" + 0.008*"democrat" + 0.008*"wall" + 0.008*"build"'), (1, '0.024*"like" + 0.011*"black" + 0.009*"would" + 0.008*"dont" + 0.008*"prank" + 0.007*"white" + 0.006*"way" + 0.006*"get" + 0.006*"family" + 0.006*"still"'), (2, '0.041*"car" + 0.015*"get" + 0.014*"would" + 0.012*"term" + 0.011*"immigrant" + 0.011*"dont" + 0.009*"racist" + 0.009*"want" + 0.008*"equal" + 0.008*"word"'), (3, '0.023*"people" + 0.017*"world" + 0.010*"refugee" + 0.008*"europe" + 0.008*"nothing" + 0.008*"need" + 0.006*"back" + 0.006*"would" + 0.006*"time" + 0.006*"video"'), (4, '0.018*"fat" + 0.014*"want" + 0.011*"protecting" + 0.011*"come" + 0.011*"gay" + 0.011*"pig" + 0.010*"gun" + 0.007*"would" + 0.007*"victim" + 0.007*"president"'), (5, '0.025*"country" + 0.020*"dont" + 0.015*"one" + 0.014*"people" + 0.010*"cake" + 0.010*"want" + 0.010*"work" + 0.008*"time" + 0.008*"gay" + 0.007*"care"'), (6, '0.021*

## Word Frequency

In [56]:
import nltk

In [74]:
wordfreq = {}
for sentence in corpus:
    tokens = sentence.split()
    for token in tokens:
        if token not in wordfreq.keys():
            wordfreq[token] = 1
        else:
            wordfreq[token] += 1

In [75]:
wordfreq['cannot']

4

In [76]:
print(wordfreq)

{'car': 27, 'hide': 4, 'engine': 2, 'would': 42, 'get': 56, 'killedthat': 2, 'stupid': 10, 'way': 41, 'smuggle': 2, 'another': 10, 'country': 59, 'build': 10, 'wall': 13, 'deport': 6, 'jon': 1, 'snow': 1, 'king': 3, 'north': 7, 'thank': 6, 'uploading': 1, 'one': 40, 'small': 3, 'complaint': 1, 'talking': 4, 'deporting': 2, 'illegal': 27, 'immigrant': 26, 'general': 3, 'title': 5, 'might': 5, 'mislead': 1, 'informed': 1, 'stopping': 1, 'immigration': 13, 'done': 9, 'year': 18, 'ago': 3, 'turned': 2, 'beloved': 1, 'los': 2, 'angeles': 2, 'turn': 9, 'filthy': 4, 'mexican': 11, 'border': 12, 'town': 2, 'complete': 3, 'latino': 2, 'gang': 3, 'million': 17, 'undocumented': 4, 'uneducated': 1, 'povertystricken': 1, 'alien': 13, 'absolutely': 5, 'nothing': 14, 'add': 4, 'quality': 2, 'life': 23, 'strong': 2, 'back': 15, 'proclivity': 1, 'dozen': 4, 'baby': 3, 'become': 6, 'legal': 6, 'citizen': 10, 'due': 3, 'insane': 2, 'law': 21, 'forcing': 1, 'california': 5, 'teacher': 2, 'teach': 1, 'nati

## Bag of Words

In [77]:
import heapq
most_freq = heapq.nlargest(200, wordfreq, key=wordfreq.get)

In [78]:
sentence_vectors = []
for sentence in corpus:
    sentence_tokens = nltk.word_tokenize(sentence)
    sent_vec = []
    for token in most_freq:
        if token in sentence_tokens:
            sent_vec.append(1)
        else:
            sent_vec.append(0)
    sentence_vectors.append(sent_vec)

In [79]:
print(sentence_vectors)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 

#### Matrix Form

In [80]:
import numpy as np
sentence_vectors_Matrix = np.asarray(sentence_vectors)

In [81]:
print(sentence_vectors_Matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


## Ngrams

#### Unigrams

In [82]:
import re
import collections
c = collections.Counter(wordfreq)
c.most_common(100)

[('people', 105),
 ('like', 75),
 ('dont', 61),
 ('country', 59),
 ('get', 56),
 ('want', 44),
 ('would', 42),
 ('way', 41),
 ('one', 40),
 ('gay', 40),
 ('trump', 38),
 ('right', 36),
 ('muslim', 34),
 ('refugee', 33),
 ('say', 32),
 ('know', 32),
 ('good', 31),
 ('think', 31),
 ('world', 28),
 ('car', 27),
 ('illegal', 27),
 ('time', 27),
 ('thing', 27),
 ('immigrant', 26),
 ('need', 26),
 ('racist', 26),
 ('make', 26),
 ('see', 25),
 ('take', 24),
 ('video', 24),
 ('let', 24),
 ('life', 23),
 ('culture', 23),
 ('come', 23),
 ('black', 23),
 ('even', 23),
 ('going', 22),
 ('white', 22),
 ('fucking', 22),
 ('law', 21),
 ('american', 21),
 ('said', 21),
 ('heart', 21),
 ('love', 21),
 ('government', 20),
 ('url', 20),
 ('many', 20),
 ('religion', 20),
 ('doe', 19),
 ('islam', 19),
 ('man', 19),
 ('doesnt', 19),
 ('fuck', 19),
 ('year', 18),
 ('america', 18),
 ('thats', 18),
 ('million', 17),
 ('europe', 17),
 ('hate', 17),
 ('shit', 17),
 ('woman', 17),
 ('every', 16),
 ('president', 1

#### Bigrams

In [83]:
from nltk import word_tokenize
from nltk.util import ngrams
from nltk import FreqDist

bigramfdist = FreqDist()
for text in corpus:
    if(len(text)>1):
        token = nltk.word_tokenize(text)
        bigrams = ngrams(token,2)
        bigramfdist.update(bigrams)

In [84]:
list(bigramfdist)

[('car', 'car'),
 ('hide', 'engine'),
 ('engine', 'would'),
 ('would', 'get'),
 ('get', 'killedthat'),
 ('killedthat', 'stupid'),
 ('stupid', 'way'),
 ('way', 'smuggle'),
 ('smuggle', 'another'),
 ('another', 'country'),
 ('build', 'wall'),
 ('wall', 'deport'),
 ('jon', 'snow'),
 ('snow', 'king'),
 ('king', 'north'),
 ('north', 'thank'),
 ('thank', 'uploading'),
 ('uploading', 'one'),
 ('one', 'small'),
 ('small', 'complaint'),
 ('complaint', 'talking'),
 ('talking', 'deporting'),
 ('deporting', 'illegal'),
 ('illegal', 'immigrant'),
 ('immigrant', 'immigrant'),
 ('immigrant', 'general'),
 ('general', 'title'),
 ('title', 'might'),
 ('might', 'mislead'),
 ('mislead', 'informed'),
 ('stopping', 'illegal'),
 ('illegal', 'immigration'),
 ('immigration', 'done'),
 ('done', 'year'),
 ('year', 'ago'),
 ('ago', 'turned'),
 ('turned', 'beloved'),
 ('beloved', 'los'),
 ('los', 'angeles'),
 ('angeles', 'turn'),
 ('turn', 'filthy'),
 ('filthy', 'mexican'),
 ('mexican', 'border'),
 ('border', 'tow

In [85]:
bigramfdist.most_common(10)

[(('car', 'car'), 15),
 (('illegal', 'immigrant'), 14),
 (('middle', 'east'), 9),
 (('build', 'wall'), 7),
 (('donald', 'trump'), 7),
 (('get', 'rid'), 6),
 (('black', 'people'), 6),
 (('gay', 'people'), 6),
 (('poor', 'country'), 5),
 (('dont', 'care'), 5)]

#### Trigrams

In [86]:
threeramfdist = FreqDist()

for text in corpus:
    if(len(text)>1):
        token = nltk.word_tokenize(text)
        if len(token)>2:
            trigrams = ngrams(token,3)
            threeramfdist.update(trigrams)

In [87]:
list(threeramfdist)

[('car', 'car', 'car'),
 ('hide', 'engine', 'would'),
 ('engine', 'would', 'get'),
 ('would', 'get', 'killedthat'),
 ('get', 'killedthat', 'stupid'),
 ('killedthat', 'stupid', 'way'),
 ('stupid', 'way', 'smuggle'),
 ('way', 'smuggle', 'another'),
 ('smuggle', 'another', 'country'),
 ('build', 'wall', 'deport'),
 ('jon', 'snow', 'king'),
 ('snow', 'king', 'north'),
 ('king', 'north', 'thank'),
 ('north', 'thank', 'uploading'),
 ('thank', 'uploading', 'one'),
 ('uploading', 'one', 'small'),
 ('one', 'small', 'complaint'),
 ('small', 'complaint', 'talking'),
 ('complaint', 'talking', 'deporting'),
 ('talking', 'deporting', 'illegal'),
 ('deporting', 'illegal', 'immigrant'),
 ('illegal', 'immigrant', 'immigrant'),
 ('immigrant', 'immigrant', 'general'),
 ('immigrant', 'general', 'title'),
 ('general', 'title', 'might'),
 ('title', 'might', 'mislead'),
 ('might', 'mislead', 'informed'),
 ('stopping', 'illegal', 'immigration'),
 ('illegal', 'immigration', 'done'),
 ('immigration', 'done', 'y

In [88]:
threeramfdist.most_common(10)

[(('car', 'car', 'car'), 10),
 (('hide', 'engine', 'would'), 2),
 (('engine', 'would', 'get'), 2),
 (('would', 'get', 'killedthat'), 2),
 (('get', 'killedthat', 'stupid'), 2),
 (('killedthat', 'stupid', 'way'), 2),
 (('stupid', 'way', 'smuggle'), 2),
 (('way', 'smuggle', 'another'), 2),
 (('smuggle', 'another', 'country'), 2),
 (('exact', 'thing', 'happen'), 2)]

### @ekarati